### ISSUE TITLE
Enable Explicit Joint-to-CAN ID Mapping via ros__parameters

### ISSUE THREAD

**Issue by cr0Kz** [Arctos-Robotics/ros2_arctos#13]
### **Description**
Enable the specification of CAN IDs for each joint using a structured `ros__parameters` configuration. This approach would define joints as a list with their names and associated CAN IDs, ensuring clarity and flexibility in the robot arm's setup.

### **Motivation**
This enhancement provides a clean and organized method to configure joints and their CAN IDs, making the system more intuitive and adaptable. It supports scenarios where users may operate only certain joints due to incomplete builds or maintenance needs. By moving away from index-based setups, this feature increases usability and reduces potential errors during configuration.

### **Use Case**
- **Incremental Builds**: A user has only built part of the arm (e.g., joints Y, Z, and A) and wants to operate those without configuring non-functional joints (X, B, and C).
- **Custom Hardware Configurations**: Users with unique setups can remap joint names and CAN IDs as needed without modifying the underlying code or URDF.
- **Maintenance and Debugging**: Users can temporarily exclude specific joints by omitting them from the configuration while working with the remaining functional joints.

### **Proposed Solution**
Define the joint-to-CAN ID mapping in the `ros__parameters` configuration as a list of dictionaries. For example:

```yaml
joints:
  - name: X_joint
    can_id: 1
  - name: Y_joint
    can_id: 2
  - name: Z_joint
    can_id: 3
  - name: A_joint
    can_id: 4
  - name: B_joint
    can_id: 5
  - name: C_joint
    can_id: 6
```

The robot software would then iterate through this list to configure the joints dynamically at runtime. This approach ensures each joint is explicitly defined, with room for adjustments or omissions as needed.

### **Alternatives**
- **Flat Key-Value Structure**: Use a key-value format with joint names as keys and CAN IDs as values. While simpler, this lacks the extensibility of the proposed list structure:
  ```yaml
  joints:
    X_joint: 1
    Y_joint: 2
    Z_joint: 3
  ```
- **URDF-Based Specification**: Define CAN IDs within the URDF file. This tightly couples configuration to the URDF, making dynamic adjustments more challenging.

### **Additional Context**
Using a structured list in `ros__parameters` aligns with ROS2's flexible configuration style. It allows for future expansion (e.g., adding more properties like limits or offsets) and simplifies partial builds. Clear documentation and examples in the robot's setup guide would enhance user understanding and adoption.

Reference: #10  and #3 as this may impact how we retrieve the can_id.
